#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE keycloak;
  CREATE DATABASE oms_products;
  CREATE DATABASE oms_orders;
  CREATE DATABASE oms_payments;
  CREATE DATABASE oms_users;

  GRANT ALL PRIVILEGES ON DATABASE keycloak TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE oms_products TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE oms_orders TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE oms_payments TO "$POSTGRES_USER";
  GRANT ALL PRIVILEGES ON DATABASE oms_users TO "$POSTGRES_USER";
EOSQL